# QCArchive Demonstration

MolSSI Software Summer School - Day 2

In [25]:
import numpy as np

In [6]:
import qcportal as ptl

client = ptl.FractalClient()

In [8]:
client

FractalClient(server_name='The MolSSI QCArchive Server', address='https://api.qcarchive.molssi.org:443/', username='None')

In [10]:
butane = client.query_molecules(id=['61139', '70659'])

In [11]:
butane

[<Molecule(name='C4H10' formula='C4H10' hash='3bbc6db')>,
 <Molecule(name='C4H10' formula='C4H10' hash='bb665a3')>]

In [12]:
butane[0].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [13]:
butane[1].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [14]:
dir(butane)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [16]:
butane[0].symbols

['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

In [17]:
butane[0].geometry

array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]])

In [21]:
coords = {}
for i in enumerate(butane[0].symbols):
    coords[i] = butane[0].geometry[i]
coords

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [18]:
butane_geometries = [butane[0].geometry.copy(), butane[1].geometry.copy()]

In [37]:
print(butane_geometries)

[array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]]), array([[-0.69390481, -2.34149626, -1.69148799],
       [-1.52276705,  2.12200941,  1.41576994],
       [ 1.67240752, -1.04497304, -0.64735584],
       [ 1.23080507,  1.33319296,  1.00805961],
       [-1.91853592, -3.01948807, -0.12936141],
       [-1.76605429, -1.03734012, -2.93620015],
       [-0.12310659, -4.00556366, -2.

In [23]:
def calculate_distance(rA, rB):
    """Calculate the distance between points A and B"""
    dist_vec = (rA - rB)
    distance = np.linalg.norm(dist_vec)
    return distance

In [39]:
atom1 = butane_geometries[0][0]
print(atom1)

[ 0.60309252 -2.0666753  -2.95631542]


In [40]:
atom2 = butane_geometries[0][1]
print(atom2)

[-0.54975128  2.07257294  2.96267825]


In [31]:
def build_bond_list(coordinates, max_bond=3, min_bond=0):
    num_atoms = len(coordinates)
    
    bonds = {}
    
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance
    
    return bonds

In [51]:
bond_list = build_bond_list(butane_geometries[0], max_bond=2.93)
bond_list

{(0, 2): 2.873020656801253,
 (0, 4): 2.068839651551603,
 (0, 5): 2.068484041315794,
 (0, 6): 2.068821759435787,
 (1, 3): 2.873059651780396,
 (1, 7): 2.068247482474781,
 (1, 8): 2.0685780442929644,
 (1, 9): 2.0687346633381822,
 (2, 3): 2.8862132661474598,
 (2, 10): 2.0715801221019885,
 (2, 11): 2.0716218178677623,
 (3, 12): 2.0713472807014583,
 (3, 13): 2.071754810836534}

In [42]:
measured_distance = calculate_distance(atom1, atom2)
print(measured_distance)

7.314158248564329


In [43]:
butane[0].measure([0, 1])

7.31415824856433

In [45]:
# Use calculate_distance funciton to measure the distance between atoms 3 and 10 in the second butane molecule
print(calculate_distance(butane_geometries[1][3], butane_geometries[1][10]))

4.120152166869724


In [47]:
butane[1].measure([3,10])

4.120152166869724

In [33]:
bond_list = build_bond_list(butane_geometries[0])

In [34]:
print(bond_list)

{(0, 2): 2.873020656801253, (0, 4): 2.068839651551603, (0, 5): 2.068484041315794, (0, 6): 2.068821759435787, (1, 3): 2.873059651780396, (1, 7): 2.068247482474781, (1, 8): 2.0685780442929644, (1, 9): 2.0687346633381822, (2, 3): 2.8862132661474598, (2, 10): 2.0715801221019885, (2, 11): 2.0716218178677623, (3, 12): 2.0713472807014583, (3, 13): 2.071754810836534}


In [30]:
butane[0].connectivity

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [36]:
import qcelemental

angstrom_to_bohr = qcelemental.constants.conversion_factor("angstrom", "bohr")

In [53]:
max_length = 1.55*angstrom_to_bohr
max_length

2.9290754944596338

In [ ]:
# Use qcportal to access a geometry optimizaiton calculation
# Use query_procedures
# id = 2658710

In [54]:
dir(client)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_automodel_request',
 '_headers',
 '_mock_network_error',
 '_repr_html_',
 '_request',
 '_verify',
 'add_collection',
 'add_compute',
 'add_keywords',
 'add_molecules',
 'add_procedure',
 'add_service',
 'address',
 'from_file',
 'get_collection',
 'list_collections',
 'query_keywords',
 'query_kvstore',
 'query_molecules',
 'query_procedures',
 'query_results',
 'query_services',
 'query_tasks',
 'server_info',
 'server_information',
 'server_name',
 'username']

In [65]:
calculation = client.query_procedures(id=['2658710'])

In [66]:
dir(calculation)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [67]:
optimization = calculation[0]

In [71]:
initial = optimization.get_initial_molecule()
initial.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [72]:
final = optimization.get_final_molecule()
final.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [73]:
initial.connectivity

In [79]:
#max bond length is 2.93

final_bonds = build_bond_list(final.geometry.copy(), max_bond=2.93)
initial_bonds = build_bond_list(initial.geometry.copy(), max_bond=2.93)

In [83]:
# Compare the two dictionaries initial_bonds and final_bonds to find the change in bond length

bond_change = {}
for i in final_bonds:
    bond_change[i] = (final_bonds[i] - initial_bonds[i])
bond_change

{(0, 1): -0.12125783998247419,
 (0, 5): 0.03652933845980799,
 (0, 54): 0.0013072821258468537,
 (1, 6): 0.0365286356592871,
 (1, 55): 0.0013065023782292684,
 (2, 3): -0.12125319998628425,
 (2, 9): 0.036530668675503364,
 (2, 56): 0.0013062416111879749,
 (3, 10): 0.0365312833547744,
 (3, 57): 0.0013068556466429015,
 (4, 5): -0.04903193300734543,
 (4, 13): -0.0490720625963279,
 (4, 58): 0.003137346014596698,
 (5, 14): 0.010798420718752144,
 (6, 7): -0.04903028628599815,
 (6, 15): 0.01079988956621758,
 (7, 16): -0.04907121615054244,
 (7, 59): 0.0031362976027144995,
 (8, 9): -0.049024471064973874,
 (8, 19): -0.04906907865232091,
 (8, 60): 0.003135298936773445,
 (9, 20): 0.010799063343710724,
 (10, 11): -0.04902644295843839,
 (10, 21): 0.010798380165098376,
 (11, 22): -0.0490686525226276,
 (11, 61): 0.003135746517670235,
 (12, 13): 0.03673448192571094,
 (12, 24): -0.12113026442271035,
 (12, 62): 0.001361072035932498,
 (13, 25): 0.010758433401821588,
 (14, 15): 0.005330890020097456,
 (14, 26):